apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: jiffymeals
  labels:
    app: eureka-server
spec: 
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: balotu/eureka:latest
        ports: 
        - containerPort: 8763

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: jiffymeals
  labels:
    app: eureka-server
spec: 
  selector:
    app: eureka-server
  ports: 
    - protocol: TCP
      port: 8763
      targetPort: 8763
      nodePort: 30002
  type: NodePort 
