apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: jiffymeals
  labels:
    app: config-server
spec: 
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: balotu/eureka:latest
        ports: 
        - containerPort: 8769

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: jiffymeals
  labels:
    app: config-server
spec: 
  selector:
    app: config-server
  ports: 
    - protocol: TCP
      port: 8762
      targetPort: 8762
      nodePort: 30001
  type: NodePort 
