apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-server
  namespace: jiffymeals
  labels:
    app: identity-server
spec: 
  selector:
    matchLabels:
      app: identity-server
  template:
    metadata:
      labels:
        app: identity-server
    spec:
      containers:
      - name: identity-server
        image: balotu/identity:latest
        ports: 
        - containerPort: 8765

---
apiVersion: v1
kind: Service
metadata:
  name: identity-server
  namespace: jiffymeals
  labels:
    app: identity-server
spec: 
  selector:
    app: identity-server
  ports: 
    - protocol: TCP
      port: 8765
      targetPort: 8765
      nodePort: 30004
  type: NodePort 
