apiVersion: apps/v1
kind: Deployment
metadata:
  name: resturant-server
  namespace: jiffymeals
  labels:
    app: resturant-server
spec: 
  selector:
    matchLabels:
      app: resturant-server
  template:
    metadata:
      labels:
        app: resturant-server
    spec:
      containers:
      - name: resturant-server
        image: balotu/restaurant:latest
        ports: 
        - containerPort: 8768

---
apiVersion: v1
kind: Service
metadata:
  name: resturant-server
  namespace: jiffymeals
  labels:
    app: resturant-server
spec: 
  selector:
    app: resturant-server
  ports: 
    - protocol: TCP
      port: 8768
      targetPort: 8768
      nodePort: 30007
  type: NodePort 
