apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-server
  namespace: jiffymeals
  labels:
    app: payment-server
spec: 
  selector:
    matchLabels:
      app: payment-server
  template:
    metadata:
      labels:
        app: payment-server
    spec:
      containers:
      - name: payment-server
        image: balotu/payment:latest
        ports: 
        - containerPort: 8767

---
apiVersion: v1
kind: Service
metadata:
  name: payment-server
  namespace: jiffymeals
  labels:
    app: payment-server
spec: 
  selector:
    app: payment-server
  ports: 
    - protocol: TCP
      port: 8767
      targetPort: 8767
      nodePort: 30006
  type: NodePort 
