piVersion: v1
kind: Service
metadata:
  name: payment-kube-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30002
  type: NodePort
