apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: jiffymeals
  labels:
    app: gateway-server
spec: 
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
      - name: gateway-server
        image: balotu/gateway:latest
        ports: 
        - containerPort: 8764

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: jiffymeals
  labels:
    app: gateway-server
spec: 
  selector:
    app: gateway-server
  ports: 
    - protocol: TCP
      port: 8764
      targetPort: 8764
      nodePort: 30003
  type: NodePort 
